export const ERROR_KEYS = {
  // Auth errors
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVALID_VERIFICATION_TOKEN: 'INVALID_VERIFICATION_TOKEN',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  RESET_TOKEN_USED: 'RESET_TOKEN_USED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Note errors
  NOTE_NOT_FOUND: 'NOTE_NOT_FOUND',
  NOTE_ACCESS_DENIED: 'NOTE_ACCESS_DENIED',

  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

export type ErrorKey = (typeof ERROR_KEYS)[keyof typeof ERROR_KEYS];
